### ISSUE TITLE
com.google.common.reflect.TypeToken isn't parameterized

### ISSUE THREAD

**Issue by SebastianEngel** [rafaelsetragni/AndroidAwnCore#3]
Hi,

after upgrading to Android Gradle Plugin version 8, R8 fullmode is now enabled by default, which brings more aggressive optimizations. Because of that running our app results in the following error:

```
E/Android: [Awesome Notifications](12551): class com.google.common.reflect.TypeToken isn't parameterized (SharedManager:58)
W/System.err(12551): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: class com.google.common.reflect.TypeToken isn't parameterized
W/System.err(12551): 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
W/System.err(12551): 	at com.google.common.reflect.TypeCapture.capture(TypeCapture.java:33)
W/System.err(12551): 	at com.google.common.reflect.TypeToken.<init>(TypeToken.java:125)
W/System.err(12551): 	at me.carda.awesome_notifications.core.utils.JsonUtils$1.<init>(JsonUtils.java:19)
W/System.err(12551): 	at me.carda.awesome_notifications.core.utils.JsonUtils.fromJson(JsonUtils.java:19)
```

I investigated and found that adding the following lines to the proguard config would help:
```
# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```

I also saw that those are already in the AndroidAwnCore's [proguardrules.pro](https://github.com/rafaelsetragni/AndroidAwnCore/blob/main/core/proguard-rules.pro#L63C1-L65C88) file.

I assume that the error still occurs because the `JsonUtils` class mentioned in the stacktrace actually [imports](https://github.com/rafaelsetragni/AndroidAwnCore/blob/main/core/src/main/java/me/carda/awesome_notifications/core/utils/JsonUtils.java#L3) `com.google.common.reflect.TypeToken`, not `import com.google.common.gson.TypeToken` as defined in the proguard keep rules. Therefore I assume the keep rules need to be adjusted to the match the `com.google.common.reflect.TypeToken` import OR the import in `JsonUtils` needs to be changed to match the current keep rules for `com.google.common.gson.TypeToken`.

A similar case was [reported](https://issuetracker.google.com/issues/247146909#comment12) in the Android issue tracker. There they solved it with wildcard usages for the keep rules.

```
-keep,allowshrinking class **.reflect.TypeToken { *; }
-keep,allowshrinking class * extends **.reflect.TypeToken
```

**Comment by ndusart** [comment]
Can be fixed by #2 :)

**Comment by rafaelsetragni** [comment]
That implementation did not fixed the minification on R8. I just accepted the merge and did real tests on it and it fails to prevent fails with minification.

**Comment by ndusart** [comment]
The issue is fixed in my case if I put these rules in the final proguard-rules.pro of the application.

Maybe, these should be defined in the [consumer-rules.pro](https://github.com/rafaelsetragni/AndroidAwnCore/blob/main/core/consumer-rules.pro) ?

**Comment by rafaelsetragni** [comment]
Yes, using [consumer-rules.pro](https://github.com/rafaelsetragni/AndroidAwnCore/blob/main/core/consumer-rules.pro) would be more accurate. However, even with this setting, the Flutter application was not processing the proguard rules correctly. Due to this, we decided to remove the Gson library entirely and replaced it with JSONObject for better compatibility.

These adjustments, along with other enhancements, are available in the latest 0.10.0 release. We recommend updating to this version to benefit from all the improvements.

**Comment by SebastianEngel** [comment]
Thanks @rafaelsetragni. Will you release an updated version of [awesome_notifications](https://github.com/rafaelsetragni/awesome_notifications) that depends on the 0.10.0, please? 🙏🏻
